import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./store.css";
import "@/css/bootstrap.min.css";
import "@/css/materialdesignicons.min.css";
import "@/css/pe-icon-7-stroke.css";
import "@/css/tiny-slider.css";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
        <script src="@/js/smooth-scroll.polyfills.min.js"></script>
        <script src="@/js/gumshoe.polyfills.min.js"></script>
        <script src="@/js/tiny-slider.js"></script>
      </body>
    </html>
  );
}
